### ISSUE TITLE
Error when loading (with willow 12.1.0)

### ISSUE THREAD

**Issue by sanjayminni** [ba-st/Willow-JQueryUI#28]
There is an error when trying to load Willow-bootstrap and willow-JQueryUI using
the Metacello script

(prior to this Willow 12.1.0 was loaded first in Pharo 8 / Windows 10)

Possibly this has something to do with the following line in setUpDependencies:
baseline: 'Willow' with: [ spec repository: 'github://ba-st/Willow:v12/source' ]

This is worked around by pulling in BaselineOfWillow-Bootstrap / JqueryUI thru iceberg, then editing Willow:v12 to Willow:12.1.0. it then successfully loads thru iceberg
right-click metacello(default)

as responded Probably v12 must be equivalent to the latest v12.x release.

**Comment by gcotelli** [comment]
Same situation described at https://github.com/ba-st/Willow-Bootstrap/issues/94
